export const MOCK_USER = {
  id: 'usr_101',
  name: 'Alex Morgan',
  email: 'alex.morgan@example.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  role: 'Explorer Member',
  location: 'San Francisco, CA',
  joinedDate: 'March 2024',
};

export const MOCK_TRIPS = [
  {
    id: 'trip_001',
    title: 'Japanese Heritage Odyssey',
    subtitle: 'Tokyo • Kyoto • Osaka',
    citiesCount: 3,
    durationDays: 12,
    startDate: '2026-10-15',
    endDate: '2026-10-27',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    status: 'Upcoming',
    statusVariant: 'primary',
    budgetTotal: 4800,
    budgetSpent: 3200,
    destinations: ['Tokyo', 'Kyoto', 'Osaka'],
    collaboratorsCount: 2,
    progressPercentage: 67,
  },
  {
    id: 'trip_002',
    title: 'Mediterranean Sun & Culture',
    subtitle: 'Barcelona • Nice • Florence',
    citiesCount: 3,
    durationDays: 14,
    startDate: '2027-04-10',
    endDate: '2027-04-24',
    coverImage: 'https://images.unsplash.com/photo-1511527667048-009699346a1b?auto=format&fit=crop&w=800&q=80',
    status: 'Planning',
    statusVariant: 'warning',
    budgetTotal: 6200,
    budgetSpent: 1800,
    destinations: ['Barcelona', 'Nice', 'Florence'],
    collaboratorsCount: 3,
    progressPercentage: 30,
  },
  {
    id: 'trip_003',
    title: 'Alpine & Lakes Escape',
    subtitle: 'Zurich • Interlaken • Geneva',
    citiesCount: 3,
    durationDays: 9,
    startDate: '2026-06-02',
    endDate: '2026-06-11',
    coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80',
    status: 'Completed',
    statusVariant: 'success',
    budgetTotal: 3900,
    budgetSpent: 3850,
    destinations: ['Zurich', 'Interlaken', 'Geneva'],
    collaboratorsCount: 1,
    progressPercentage: 100,
  },
];

export const MOCK_RECOMMENDED_DESTINATIONS = [
  {
    id: 'dest_01',
    city: 'Kyoto',
    country: 'Japan',
    tagline: 'Ancient Temples & Bamboo Groves',
    estCostPerDay: 210,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80',
    category: 'Cultural',
    rating: 4.9,
    bestMonths: 'Oct - Nov, Mar - Apr',
  },
  {
    id: 'dest_02',
    city: 'Amalfi Coast',
    country: 'Italy',
    tagline: 'Cliffside Villages & Tyrrhenian Sea',
    estCostPerDay: 320,
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
    category: 'Coastal',
    rating: 4.8,
    bestMonths: 'May - Sep',
  },
  {
    id: 'dest_03',
    city: 'Reykjavik',
    country: 'Iceland',
    tagline: 'Geysers, Glaciers & Northern Lights',
    estCostPerDay: 280,
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=600&q=80',
    category: 'Adventure',
    rating: 4.9,
    bestMonths: 'Sep - Mar',
  },
  {
    id: 'dest_04',
    city: 'Santorini',
    country: 'Greece',
    tagline: 'Whitewashed Aegean Architecture',
    estCostPerDay: 290,
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80',
    category: 'Romantic',
    rating: 4.7,
    bestMonths: 'Apr - Oct',
  },
];

export const MOCK_BUDGET_SUMMARY = {
  totalBudget: 14900,
  totalAllocated: 11000,
  totalSpent: 8850,
  currency: 'USD',
  currencySymbol: '$',
  categories: [
    { name: 'Flights & Rail', percentage: 40, amount: 3540, color: '#4F46E5' },
    { name: 'Accommodations', percentage: 35, amount: 3097, color: '#6366F1' },
    { name: 'Activities & Dining', percentage: 18, amount: 1593, color: '#F97316' },
    { name: 'Buffer & Transit', percentage: 7, amount: 620, color: '#94A3B8' },
  ],
};

export const MOCK_ACTIVITIES = [
  {
    id: 'act_1',
    text: 'Hotel confirmed in Tokyo (Shinjuku Granbell)',
    timestamp: '2 hours ago',
    icon: 'Hotel',
  },
  {
    id: 'act_2',
    text: 'Shinkansen bullet train pass booked for Kyoto-Osaka route',
    timestamp: 'Yesterday',
    icon: 'Train',
  },
  {
    id: 'act_3',
    text: 'Sarah added 4 new food recommendations to Paris itinerary',
    timestamp: '2 days ago',
    icon: 'UserPlus',
  },
];
