export const MOCK_USER = {
  id: 'usr_101',
  name: 'Alex Morgan',
  email: 'alex.morgan@example.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  role: 'Explorer Member',
  location: 'San Francisco, CA',
  joinedDate: 'March 2024',
  preferredCurrency: 'USD',
  language: 'English',
};

export const DEFAULT_COVER_IMAGES = [
  {
    name: 'Mount Fuji & Chureito Pagoda',
    url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Barcelona Sagrada Familia',
    url: 'https://images.unsplash.com/photo-1511527667048-009699346a1b?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Swiss Alps & Interlaken',
    url: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Santorini Cliffside Coast',
    url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Paris Eiffel Tower View',
    url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
  },
];

export const MOCK_CITIES = [
  {
    id: 1,
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    latitude: 48.8566,
    longitude: 2.3522,
    image_url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    description: 'The City of Light, famous for its romance, haute gastronomy, world-class art museums, and the iconic Eiffel Tower.',
    avg_daily_cost: 150.0,
    avg_meal_cost: 30.0,
    cost_index: 'Moderate', // 'Budget' | 'Moderate' | 'Luxury'
    popularity: 98,
    rating: 4.9,
    best_months: 'Apr - Jun, Sep - Nov',
    categories: ['Cultural', 'Romantic', 'Culinary'],
  },
  {
    id: 2,
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    latitude: 35.6762,
    longitude: 139.6503,
    image_url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    description: 'A dazzling ultra-modern metropolis blending neon skyscrapers, ancient historic temples, bullet trains, and Michelin-star cuisine.',
    avg_daily_cost: 130.0,
    avg_meal_cost: 20.0,
    cost_index: 'Moderate',
    popularity: 99,
    rating: 4.9,
    best_months: 'Mar - May, Oct - Nov',
    categories: ['Cultural', 'Adventure', 'Food'],
  },
  {
    id: 3,
    name: 'New York City',
    country: 'United States',
    region: 'North America',
    latitude: 40.7128,
    longitude: -74.0060,
    image_url: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800&q=80',
    description: 'The Big Apple, featuring Central Park, Broadway theaters, high-energy world-class nightlife, and iconic skyscraper skyline views.',
    avg_daily_cost: 200.0,
    avg_meal_cost: 35.0,
    cost_index: 'Luxury',
    popularity: 96,
    rating: 4.8,
    best_months: 'Apr - Jun, Sep - Nov',
    categories: ['Sightseeing', 'Entertainment', 'Culinary'],
  },
  {
    id: 4,
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    latitude: 41.9028,
    longitude: 12.4964,
    image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
    description: 'The Eternal City, renowned for millennia of history, ancient Colosseum amphitheater ruins, Vatican art, and authentic pasta.',
    avg_daily_cost: 120.0,
    avg_meal_cost: 25.0,
    cost_index: 'Moderate',
    popularity: 97,
    rating: 4.8,
    best_months: 'Apr - May, Sep - Oct',
    categories: ['Cultural', 'History', 'Culinary'],
  },
  {
    id: 5,
    name: 'Barcelona',
    country: 'Spain',
    region: 'Europe',
    latitude: 41.3851,
    longitude: 2.1734,
    image_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=800&q=80',
    description: 'Vibrant seaside city known for whimsical Gaudi architecture, Mediterranean beaches, lively tapas culture, and artistic quarters.',
    avg_daily_cost: 110.0,
    avg_meal_cost: 22.0,
    cost_index: 'Moderate',
    popularity: 95,
    rating: 4.8,
    best_months: 'May - Jun, Sep - Oct',
    categories: ['Architecture', 'Coastal', 'Culinary'],
  },
  {
    id: 6,
    name: 'London',
    country: 'United Kingdom',
    region: 'Europe',
    latitude: 51.5074,
    longitude: -0.1278,
    image_url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    description: 'Historic royal capital along the River Thames featuring Big Ben, the London Eye, West End theatres, and charming pub culture.',
    avg_daily_cost: 180.0,
    avg_meal_cost: 32.0,
    cost_index: 'Luxury',
    popularity: 94,
    rating: 4.7,
    best_months: 'May - Sep',
    categories: ['History', 'Cultural', 'Entertainment'],
  },
  {
    id: 7,
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    latitude: -8.4095,
    longitude: 115.1889,
    image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    description: 'Tropical island paradise known for emerald rice terraces, serene cliffside temples, surf beaches, and rejuvenating wellness retreats.',
    avg_daily_cost: 60.0,
    avg_meal_cost: 10.0,
    cost_index: 'Budget',
    popularity: 97,
    rating: 4.9,
    best_months: 'Apr - Oct',
    categories: ['Adventure', 'Coastal', 'Wellness'],
  },
  {
    id: 8,
    name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    latitude: -33.8688,
    longitude: 151.2093,
    image_url: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800&q=80',
    description: 'Stunning coastal harbor city home to Bondi Beach, Sydney Opera House, sunny climate, and breathtaking ocean cliff walks.',
    avg_daily_cost: 160.0,
    avg_meal_cost: 28.0,
    cost_index: 'Luxury',
    popularity: 93,
    rating: 4.8,
    best_months: 'Sep - Nov, Mar - May',
    categories: ['Coastal', 'Sightseeing', 'Adventure'],
  },
  {
    id: 9,
    name: 'Kyoto',
    country: 'Japan',
    region: 'Asia',
    latitude: 35.0116,
    longitude: 135.7681,
    image_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    description: 'The cultural soul of Japan with thousands of classical Buddhist temples, gardens, imperial palaces, and traditional geisha districts.',
    avg_daily_cost: 125.0,
    avg_meal_cost: 22.0,
    cost_index: 'Moderate',
    popularity: 98,
    rating: 4.9,
    best_months: 'Oct - Nov, Mar - Apr',
    categories: ['Cultural', 'History', 'Nature'],
  },
  {
    id: 10,
    name: 'Santorini',
    country: 'Greece',
    region: 'Europe',
    latitude: 36.3932,
    longitude: 25.4615,
    image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800&q=80',
    description: 'Iconic volcanic Aegean island with cliffhanging whitewashed cubic villages, cobalt blue domes, and legendary sunset calderas.',
    avg_daily_cost: 190.0,
    avg_meal_cost: 32.0,
    cost_index: 'Luxury',
    popularity: 96,
    rating: 4.8,
    best_months: 'Apr - Oct',
    categories: ['Romantic', 'Coastal', 'Sightseeing'],
  },
  {
    id: 11,
    name: 'Interlaken',
    country: 'Switzerland',
    region: 'Europe',
    latitude: 46.6863,
    longitude: 7.8632,
    image_url: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=800&q=80',
    description: 'Alpine wonderland nestled between Lake Thun and Lake Brienz beneath the majestic peaks of the Eiger, Mönch, and Jungfrau.',
    avg_daily_cost: 210.0,
    avg_meal_cost: 38.0,
    cost_index: 'Luxury',
    popularity: 92,
    rating: 4.9,
    best_months: 'Jun - Sep, Dec - Mar',
    categories: ['Adventure', 'Nature', 'Romantic'],
  },
  {
    id: 12,
    name: 'Reykjavik',
    country: 'Iceland',
    region: 'Europe',
    latitude: 64.1466,
    longitude: -21.9426,
    image_url: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=800&q=80',
    description: 'Gateway to surreal volcanic landscapes, natural geothermal hot springs, cascading waterfalls, and glowing Northern Lights.',
    avg_daily_cost: 195.0,
    avg_meal_cost: 35.0,
    cost_index: 'Luxury',
    popularity: 91,
    rating: 4.8,
    best_months: 'Sep - Mar (Lights), Jun - Aug (Hikes)',
    categories: ['Adventure', 'Nature', 'Wellness'],
  },
];

export const MOCK_MASTER_ACTIVITIES = [
  // Paris (city_id: 1)
  {
    id: 101,
    city_id: 1,
    cityName: 'Paris',
    country: 'France',
    title: 'Eiffel Tower Summit Access & Champagne',
    description: 'Ascend to the summit observation deck for panoramic 360-degree views across Paris with priority elevator access.',
    category: 'Sightseeing',
    cost: 32.0,
    duration_hours: 2.5,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 102,
    city_id: 1,
    cityName: 'Paris',
    country: 'France',
    title: 'Louvre Museum Timed Masterpiece Tour',
    description: 'Explore world-renowned art treasures including the Mona Lisa, Winged Victory, and Venus de Milo with an art historian.',
    category: 'Culture',
    cost: 24.0,
    duration_hours: 3.5,
    rating: 4.8,
    image_url: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 103,
    city_id: 1,
    cityName: 'Paris',
    country: 'France',
    title: 'Seine River Sunset Cruise with Live Music',
    description: 'Glide past illuminated monuments like Notre-Dame and the Musée d’Orsay while sipping French wine at twilight.',
    category: 'Experience',
    cost: 45.0,
    duration_hours: 1.5,
    rating: 4.7,
    image_url: 'https://images.unsplash.com/photo-1509299349698-ab22323ae696?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 104,
    city_id: 1,
    cityName: 'Paris',
    country: 'France',
    title: 'Montmartre Artisanal Bakery & Patisserie Walk',
    description: 'Taste fresh warm baguettes, flaky butter croissants, award-winning cheeses, and delicate macarons in bohemian alleys.',
    category: 'Food',
    cost: 55.0,
    duration_hours: 3.0,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=600&q=80',
  },

  // Tokyo (city_id: 2)
  {
    id: 201,
    city_id: 2,
    cityName: 'Tokyo',
    country: 'Japan',
    title: 'Senso-ji Temple & Asakusa Heritage Stroll',
    description: 'Visit Tokyo’s oldest historic temple, cleanse at the incense burner, and explore the buzzing Nakamise-dori shopping lane.',
    category: 'Culture',
    cost: 0.0,
    duration_hours: 2.0,
    rating: 4.8,
    image_url: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 202,
    city_id: 2,
    cityName: 'Tokyo',
    country: 'Japan',
    title: 'Shibuya Sky & Shibuya Crossing Observation',
    description: 'Experience 360-degree open-air glass views from 229 meters above Shibuya’s famous scramble crossing.',
    category: 'Sightseeing',
    cost: 25.0,
    duration_hours: 2.5,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 203,
    city_id: 2,
    cityName: 'Tokyo',
    country: 'Japan',
    title: 'Tsukiji Outer Market Gourmet Seafood Tour',
    description: 'Savor fresh melt-in-your-mouth otoro tuna sashimi, flame-torched wagyu, and tamagoyaki prepared by master artisans.',
    category: 'Food',
    cost: 65.0,
    duration_hours: 3.0,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 204,
    city_id: 2,
    cityName: 'Tokyo',
    country: 'Japan',
    title: 'teamLab Planets Immersive Digital Art',
    description: 'Wade barefoot through crystal water installations and interact with responsive floating floral light art.',
    category: 'Entertainment',
    cost: 38.0,
    duration_hours: 2.0,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
  },

  // Rome (city_id: 4)
  {
    id: 401,
    city_id: 4,
    cityName: 'Rome',
    country: 'Italy',
    title: 'Colosseum, Roman Forum & Palatine Hill Priority Entry',
    description: 'Step into the arena where gladiators battled and wander the ancient ruins of the Roman Empire Senate.',
    category: 'History',
    cost: 36.0,
    duration_hours: 3.0,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 402,
    city_id: 4,
    cityName: 'Rome',
    country: 'Italy',
    title: 'Vatican Museums & Sistine Chapel Tour',
    description: 'Admire Michelangelo’s breathtaking ceiling frescoes and the classical sculptures of the Papal collection.',
    category: 'Culture',
    cost: 42.0,
    duration_hours: 3.5,
    rating: 4.8,
    image_url: 'https://images.unsplash.com/photo-1531572753322-ad063cecc140?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 403,
    city_id: 4,
    cityName: 'Rome',
    country: 'Italy',
    title: 'Trastevere Handmade Pasta & Gelato Masterclass',
    description: 'Learn the secrets of rolling authentic fettuccine and crafting creamy Italian gelato with a local chef.',
    category: 'Food',
    cost: 75.0,
    duration_hours: 3.0,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
  },

  // Barcelona (city_id: 5)
  {
    id: 501,
    city_id: 5,
    cityName: 'Barcelona',
    country: 'Spain',
    title: 'Sagrada Familia Fast-Track & Nativity Tower Climb',
    description: 'Marvel at Antoni Gaudí’s towering stained-glass interior forest and climb the stone spiraling spires.',
    category: 'Architecture',
    cost: 38.0,
    duration_hours: 2.0,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 502,
    city_id: 5,
    cityName: 'Barcelona',
    country: 'Spain',
    title: 'Park Güell Monumental Zone Pass',
    description: 'Stroll through the whimsical mosaic salamanders, winding stone colonnades, and panoramic sea vistas.',
    category: 'Sightseeing',
    cost: 16.0,
    duration_hours: 2.0,
    rating: 4.7,
    image_url: 'https://images.unsplash.com/photo-1564221710304-0b37c8b9d729?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 503,
    city_id: 5,
    cityName: 'Barcelona',
    country: 'Spain',
    title: 'Gothic Quarter Tapas Crawl & Sangria Tasting',
    description: 'Discover hidden medieval bodegas, Iberico ham, patatas bravas, and Spanish vermouth with a local guide.',
    category: 'Food',
    cost: 58.0,
    duration_hours: 3.0,
    rating: 4.8,
    image_url: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=600&q=80',
  },

  // New York City (city_id: 3)
  {
    id: 301,
    city_id: 3,
    cityName: 'New York City',
    country: 'United States',
    title: 'SUMMIT One Vanderbilt Experiential Deck',
    description: 'Mirrored glass infinity rooms and boundless skyline views overlooking the Chrysler Building and Central Park.',
    category: 'Sightseeing',
    cost: 48.0,
    duration_hours: 2.0,
    rating: 4.8,
    image_url: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 302,
    city_id: 3,
    cityName: 'New York City',
    country: 'United States',
    title: 'Broadway Musical Evening Ticket',
    description: 'Experience an unforgettable award-winning theatrical spectacle live on 42nd Street.',
    category: 'Entertainment',
    cost: 125.0,
    duration_hours: 3.0,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=600&q=80',
  },

  // Kyoto (city_id: 9)
  {
    id: 901,
    city_id: 9,
    cityName: 'Kyoto',
    country: 'Japan',
    title: 'Fushimi Inari 10,000 Torii Gate Sunrise Trek',
    description: 'Walk through thousands of Vermilion red gates up Mount Inari before the morning crowds arrive.',
    category: 'Adventure',
    cost: 0.0,
    duration_hours: 2.5,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 902,
    city_id: 9,
    cityName: 'Kyoto',
    country: 'Japan',
    title: 'Arashiyama Bamboo Grove & Zen Matcha Ceremony',
    description: 'Listen to the rustling towering green bamboo grove followed by a meditative tea tasting ceremony.',
    category: 'Culture',
    cost: 28.0,
    duration_hours: 2.0,
    rating: 4.8,
    image_url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=600&q=80',
  },

  // Bali (city_id: 7)
  {
    id: 701,
    city_id: 7,
    cityName: 'Bali',
    country: 'Indonesia',
    title: 'Ubud Rice Terraces & Jungle Swing',
    description: 'Soar over the lush palm ravines of Tegallalang and explore traditional irrigation landscape art.',
    category: 'Adventure',
    cost: 25.0,
    duration_hours: 3.0,
    rating: 4.8,
    image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
  },
  {
    id: 702,
    city_id: 7,
    cityName: 'Bali',
    country: 'Indonesia',
    title: 'Uluwatu Sunset Temple & Kecak Fire Dance',
    description: 'Perched on a 70-meter cliff above crashing ocean waves, witness the hypnotic sunset fire chorus.',
    category: 'Culture',
    cost: 20.0,
    duration_hours: 2.5,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
  },

  // Interlaken (city_id: 11)
  {
    id: 1101,
    city_id: 11,
    cityName: 'Interlaken',
    country: 'Switzerland',
    title: 'Jungfraujoch Top of Europe Cogwheel Expedition',
    description: 'Travel by mountain railway to Europe’s highest train station, ice palace, and Aletsch Glacier.',
    category: 'Adventure',
    cost: 160.0,
    duration_hours: 5.0,
    rating: 4.9,
    image_url: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=600&q=80',
  },
];

export const INITIAL_TRIPS = [
  {
    id: 'trip_001',
    publicId: '9b691066-f2a8-44ff-bccf-2fe99a18aec6',
    title: 'European Grand Discovery Tour',
    description: 'An epic 10-day journey exploring romantic Paris, timeless Rome, and sun-drenched Barcelona with high-speed rail links and curated culinary stops.',
    subtitle: 'Paris • Rome • Barcelona',
    citiesCount: 3,
    durationDays: 10,
    startDate: '2026-10-15',
    endDate: '2026-10-24',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    status: 'Upcoming',
    statusVariant: 'primary',
    budgetTotal: 2500,
    budgetSpent: 1680,
    isPublic: true,
    destinations: ['Paris', 'Rome', 'Barcelona'],
    collaboratorsCount: 2,
    progressPercentage: 65,
    stops: [
      {
        id: 'stop_101',
        cityName: 'Paris',
        country: 'France',
        startDate: '2026-10-15',
        endDate: '2026-10-18',
        orderIndex: 0,
        transportMode: 'Flight to Charles de Gaulle',
        transportCost: 250,
        stayCostPerNight: 120,
        notes: 'Hotel in 7th arrondissement near Eiffel Tower. Pre-purchased museum pass.',
        activities: [
          {
            id: 'act_101',
            title: 'Eiffel Tower Summit Access & Champagne',
            date: '2026-10-16',
            time: '06:30 PM',
            cost: 32,
            category: 'Sightseeing',
            description: 'Sunset booking reserved for 6:30 PM overlooking the illuminated Champ de Mars.',
            isCompleted: true,
          },
          {
            id: 'act_102',
            title: 'Louvre Museum Timed Masterpiece Tour',
            date: '2026-10-17',
            time: '09:30 AM',
            cost: 24,
            category: 'Culture',
            description: 'Morning entry at 9:30 AM before general admission rush.',
            isCompleted: false,
          },
          {
            id: 'act_103',
            title: 'Montmartre Bakery Walking Tour',
            date: '2026-10-18',
            time: '11:00 AM',
            cost: 55,
            category: 'Food',
            description: 'Sample artisan pain au chocolat, warm baguettes, and macarons.',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop_102',
        cityName: 'Rome',
        country: 'Italy',
        startDate: '2026-10-18',
        endDate: '2026-10-21',
        orderIndex: 1,
        transportMode: 'High-speed Rail / Flight',
        transportCost: 90,
        stayCostPerNight: 95,
        notes: 'Stay in Trastevere neighborhood for authentic evening osterias and piazza life.',
        activities: [
          {
            id: 'act_104',
            title: 'Colosseum & Roman Forum Priority Entry',
            date: '2026-10-19',
            time: '10:00 AM',
            cost: 36,
            category: 'History',
            description: 'Guided tour of the gladiatorial amphitheater and ancient imperial forum ruins.',
            isCompleted: false,
          },
          {
            id: 'act_105',
            title: 'Trastevere Handmade Pasta & Gelato Class',
            date: '2026-10-20',
            time: '04:00 PM',
            cost: 75,
            category: 'Food',
            description: 'Cook authentic carbonara and fresh gelato from scratch.',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop_103',
        cityName: 'Barcelona',
        country: 'Spain',
        startDate: '2026-10-21',
        endDate: '2026-10-24',
        orderIndex: 2,
        transportMode: 'Flight to El Prat',
        transportCost: 110,
        stayCostPerNight: 105,
        notes: 'Boutique hotel near Gothic Quarter and Barceloneta Beach.',
        activities: [
          {
            id: 'act_106',
            title: 'Sagrada Familia Fast-Track & Tower Access',
            date: '2026-10-22',
            time: '10:30 AM',
            cost: 38,
            category: 'Architecture',
            description: 'Audio-guided tour through Gaudí’s basilica and Nativity tower climb.',
            isCompleted: false,
          },
          {
            id: 'act_107',
            title: 'Gothic Quarter Tapas Crawl',
            date: '2026-10-23',
            time: '07:30 PM',
            cost: 58,
            category: 'Food',
            description: 'Sample patatas bravas, jamón ibérico, and Catalan sangria.',
            isCompleted: false,
          },
        ],
      },
    ],
    expenses: [
      {
        id: 'exp_01',
        category: 'Other',
        amount: 50,
        date: '2026-10-16',
        description: 'Travel eSIM & Metro passes',
      },
    ],
  },
  {
    id: 'trip_002',
    publicId: '7a12b899-e4d1-41bb-98f1-8cb51920de44',
    title: 'Japanese Heritage & Neon Odyssey',
    description: 'An immersive journey through the heart of Japan exploring neon Tokyo skyscrapers, tranquil Kyoto temples, and street food in Osaka.',
    subtitle: 'Tokyo • Kyoto',
    citiesCount: 2,
    durationDays: 8,
    startDate: '2027-04-10',
    endDate: '2027-04-17',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    status: 'Planning',
    statusVariant: 'warning',
    budgetTotal: 3400,
    budgetSpent: 920,
    isPublic: true,
    destinations: ['Tokyo', 'Kyoto'],
    collaboratorsCount: 2,
    progressPercentage: 28,
    stops: [
      {
        id: 'stop_201',
        cityName: 'Tokyo',
        country: 'Japan',
        startDate: '2027-04-10',
        endDate: '2027-04-14',
        orderIndex: 0,
        transportMode: 'Flight',
        transportCost: 750,
        stayCostPerNight: 140,
        notes: 'Shinjuku hotel with direct airport limousine bus.',
        activities: [
          {
            id: 'act_201',
            title: 'teamLab Planets Immersive Art',
            date: '2027-04-11',
            time: '02:00 PM',
            cost: 38,
            category: 'Entertainment',
            description: 'Digital body-immersive mirror installation.',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop_202',
        cityName: 'Kyoto',
        country: 'Japan',
        startDate: '2027-04-14',
        endDate: '2027-04-17',
        orderIndex: 1,
        transportMode: 'Shinkansen Bullet Train',
        transportCost: 130,
        stayCostPerNight: 180,
        notes: 'Traditional Ryokan stay near Gion.',
        activities: [],
      },
    ],
    expenses: [],
  },
  {
    id: 'trip_003',
    publicId: '3c88e910-410a-42cd-9132-ff4591a27e88',
    title: 'Alpine Swiss Lakes & Glacier Peaks',
    description: 'Breathtaking mountain peaks, pristine azure lakes, and cogwheel train routes across the Swiss Alps.',
    subtitle: 'Interlaken • Zurich',
    citiesCount: 2,
    durationDays: 6,
    startDate: '2026-06-02',
    endDate: '2026-06-07',
    coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
    status: 'Completed',
    statusVariant: 'success',
    budgetTotal: 2900,
    budgetSpent: 2840,
    isPublic: true,
    destinations: ['Interlaken', 'Zurich'],
    collaboratorsCount: 1,
    progressPercentage: 100,
    stops: [
      {
        id: 'stop_301',
        cityName: 'Interlaken',
        country: 'Switzerland',
        startDate: '2026-06-02',
        endDate: '2026-06-05',
        orderIndex: 0,
        transportMode: 'Flight & Scenic Rail',
        transportCost: 550,
        stayCostPerNight: 210,
        notes: 'Mountain view chalet.',
        activities: [],
      },
    ],
    expenses: [],
  },
];

export const MOCK_TRIPS = INITIAL_TRIPS;

export const MOCK_SAVED_DESTINATIONS = [
  {
    id: 'sd_1',
    cityId: 9,
    cityName: 'Kyoto',
    country: 'Japan',
    image_url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80',
    savedAt: '2 days ago',
    avgDailyCost: 125,
  },
  {
    id: 'sd_2',
    cityId: 10,
    cityName: 'Santorini',
    country: 'Greece',
    image_url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80',
    savedAt: '1 week ago',
    avgDailyCost: 190,
  },
  {
    id: 'sd_3',
    cityId: 7,
    cityName: 'Bali',
    country: 'Indonesia',
    image_url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
    savedAt: '3 weeks ago',
    avgDailyCost: 60,
  },
];

export const MOCK_RECOMMENDED_DESTINATIONS = MOCK_CITIES.slice(0, 4);

export const MOCK_BUDGET_SUMMARY = {
  totalBudget: 14900,
  totalAllocated: 11000,
  totalSpent: 8850,
  currency: 'USD',
  currencySymbol: '$',
  categories: [
    { name: 'Flights & Transit', percentage: 38, amount: 3360, color: '#4F46E5' },
    { name: 'Accommodations', percentage: 36, amount: 3186, color: '#6366F1' },
    { name: 'Activities & Tours', percentage: 14, amount: 1239, color: '#F97316' },
    { name: 'Meals & Dining', percentage: 12, amount: 1065, color: '#10B981' },
  ],
};

export const MOCK_ACTIVITIES = [
  {
    id: 'act_1',
    text: 'Hotel confirmed in Paris (7th Arrondissement)',
    timestamp: '2 hours ago',
    icon: 'Hotel',
  },
  {
    id: 'act_2',
    text: 'Colosseum priority fast-track tickets reserved for Rome stop',
    timestamp: 'Yesterday',
    icon: 'Ticket',
  },
  {
    id: 'act_3',
    text: 'Sagrada Familia tower access added to Barcelona stop',
    timestamp: '2 days ago',
    icon: 'Compass',
  },
];

