export const MOCK_USER = {
  id: 'usr_101',
  name: 'Alex Morgan',
  email: 'alex.morgan@example.com',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
  role: 'Explorer Member',
  location: 'San Francisco, CA',
  joinedDate: 'March 2024',
};

export const DEFAULT_COVER_IMAGES = [
  {
    name: 'Mount Fuji & Chureito Pagoda',
    url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Barcelona Sagrada Familia',
    url: 'https://images.unsplash.com/photo-1511527667048-009699346a1b?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Swiss Alps & Interlaken',
    url: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Santorini Cliffside Coast',
    url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
  },
  {
    name: 'Paris Eiffel Tower View',
    url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
  },
];

export const INITIAL_TRIPS = [
  {
    id: 'trip_001',
    title: 'Japanese Heritage Odyssey',
    description: 'An immersive multi-city journey across Japan exploring historic temples, bustling neon metropolis, bullet trains, and world-class cuisine.',
    subtitle: 'Tokyo • Kyoto • Osaka',
    citiesCount: 3,
    durationDays: 12,
    startDate: '2026-10-15',
    endDate: '2026-10-27',
    coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    status: 'Upcoming',
    statusVariant: 'primary',
    budgetTotal: 4800,
    budgetSpent: 3200,
    destinations: ['Tokyo', 'Kyoto', 'Osaka'],
    collaboratorsCount: 2,
    progressPercentage: 67,
    stops: [
      {
        id: 'stop_101',
        cityName: 'Tokyo',
        country: 'Japan',
        startDate: '2026-10-15',
        endDate: '2026-10-19',
        orderIndex: 0,
        transportMode: 'Flight to Haneda',
        transportCost: 750,
        stayCostPerNight: 180,
        notes: 'Staying at Shinjuku Granbell Hotel near Yamanote line.',
        activities: [
          {
            id: 'act_101',
            title: 'Senso-ji Temple & Asakusa Walking Tour',
            date: '2026-10-16',
            time: '09:00 AM',
            cost: 25,
            category: 'Cultural',
            description: 'Explore Tokyo’s oldest Buddhist temple and Nakamise street.',
            isCompleted: true,
          },
          {
            id: 'act_102',
            title: 'Shibuya Crossing & Skytree Observation Deck',
            date: '2026-10-17',
            time: '03:30 PM',
            cost: 35,
            category: 'Sightseeing',
            description: 'Sunset view over Tokyo skyline from 450m above.',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop_102',
        cityName: 'Kyoto',
        country: 'Japan',
        startDate: '2026-10-20',
        endDate: '2026-10-23',
        orderIndex: 1,
        transportMode: 'Shinkansen Bullet Train',
        transportCost: 140,
        stayCostPerNight: 210,
        notes: 'Traditional Ryokan stay with private Onsen in Gion district.',
        activities: [
          {
            id: 'act_103',
            title: 'Fushimi Inari Taisha Early Hike',
            date: '2026-10-21',
            time: '07:00 AM',
            cost: 0,
            category: 'Adventure',
            description: 'Hike through 10,000 orange Torii gates before crowds arrive.',
            isCompleted: false,
          },
          {
            id: 'act_104',
            title: 'Arashiyama Bamboo Grove & Tea Ceremony',
            date: '2026-10-22',
            time: '11:00 AM',
            cost: 20,
            category: 'Cultural',
            description: 'Scenic bamboo forest walk followed by traditional Matcha tea.',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop_103',
        cityName: 'Osaka',
        country: 'Japan',
        startDate: '2026-10-24',
        endDate: '2026-10-27',
        orderIndex: 2,
        transportMode: 'Local Express Rail',
        transportCost: 20,
        stayCostPerNight: 150,
        notes: 'Dotonbori food district & Osaka Castle area.',
        activities: [
          {
            id: 'act_105',
            title: 'Dotonbori Street Food Tour & Takoyaki Tasting',
            date: '2026-10-25',
            time: '06:00 PM',
            cost: 45,
            category: 'Dining',
            description: 'Sample local street delicacies along the vibrant neon canal.',
            isCompleted: false,
          },
        ],
      },
    ],
  },
  {
    id: 'trip_002',
    title: 'Mediterranean Sun & Culture',
    description: 'A coastal European journey stopping through Spain, France, and Italy.',
    subtitle: 'Barcelona • Nice • Florence',
    citiesCount: 3,
    durationDays: 14,
    startDate: '2027-04-10',
    endDate: '2027-04-24',
    coverImage: 'https://images.unsplash.com/photo-1511527667048-009699346a1b?auto=format&fit=crop&w=1200&q=80',
    status: 'Planning',
    statusVariant: 'warning',
    budgetTotal: 6200,
    budgetSpent: 1800,
    destinations: ['Barcelona', 'Nice', 'Florence'],
    collaboratorsCount: 3,
    progressPercentage: 30,
    stops: [
      {
        id: 'stop_201',
        cityName: 'Barcelona',
        country: 'Spain',
        startDate: '2027-04-10',
        endDate: '2027-04-15',
        orderIndex: 0,
        transportMode: 'Flight',
        transportCost: 650,
        stayCostPerNight: 160,
        notes: 'Eixample district hotel near Passeig de Gràcia.',
        activities: [
          {
            id: 'act_201',
            title: 'Sagrada Familia Fast-Track Guided Tour',
            date: '2027-04-11',
            time: '10:00 AM',
            cost: 40,
            category: 'Sightseeing',
            description: 'Gaudi masterpiece cathedral exploration with tower access.',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop_202',
        cityName: 'Nice',
        country: 'France',
        startDate: '2027-04-16',
        endDate: '2027-04-19',
        orderIndex: 1,
        transportMode: 'Flight',
        transportCost: 110,
        stayCostPerNight: 190,
        notes: 'Promenade des Anglais seaside hotel.',
        activities: [],
      },
      {
        id: 'stop_203',
        cityName: 'Florence',
        country: 'Italy',
        startDate: '2027-04-20',
        endDate: '2027-04-24',
        orderIndex: 2,
        transportMode: 'High-speed Train',
        transportCost: 95,
        stayCostPerNight: 180,
        notes: 'Historic city center apartment.',
        activities: [],
      },
    ],
  },
  {
    id: 'trip_003',
    title: 'Alpine & Lakes Escape',
    description: 'Breathtaking mountain peaks, serene lakes, and scenic train routes across Switzerland.',
    subtitle: 'Zurich • Interlaken • Geneva',
    citiesCount: 3,
    durationDays: 9,
    startDate: '2026-06-02',
    endDate: '2026-06-11',
    coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1200&q=80',
    status: 'Completed',
    statusVariant: 'success',
    budgetTotal: 3900,
    budgetSpent: 3850,
    destinations: ['Zurich', 'Interlaken', 'Geneva'],
    collaboratorsCount: 1,
    progressPercentage: 100,
    stops: [
      {
        id: 'stop_301',
        cityName: 'Zurich',
        country: 'Switzerland',
        startDate: '2026-06-02',
        endDate: '2026-06-04',
        orderIndex: 0,
        transportMode: 'Flight',
        transportCost: 800,
        stayCostPerNight: 240,
        notes: 'Old Town hotel.',
        activities: [],
      },
      {
        id: 'stop_302',
        cityName: 'Interlaken',
        country: 'Switzerland',
        startDate: '2026-06-05',
        endDate: '2026-06-08',
        orderIndex: 1,
        transportMode: 'SBB Scenic Train',
        transportCost: 60,
        stayCostPerNight: 220,
        notes: 'Mountain chalet with Eiger view.',
        activities: [],
      },
      {
        id: 'stop_303',
        cityName: 'Geneva',
        country: 'Switzerland',
        startDate: '2026-06-09',
        endDate: '2026-06-11',
        orderIndex: 2,
        transportMode: 'Train',
        transportCost: 50,
        stayCostPerNight: 210,
        notes: 'Lakeside hotel.',
        activities: [],
      },
    ],
  },
];

export const MOCK_TRIPS = INITIAL_TRIPS;

export const MOCK_RECOMMENDED_DESTINATIONS = [
  {
    id: 'dest_01',
    city: 'Kyoto',
    country: 'Japan',
    tagline: 'Ancient Temples & Bamboo Groves',
    estCostPerDay: 210,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=600&q=80',
    category: 'Cultural',
    rating: 4.9,
    bestMonths: 'Oct - Nov, Mar - Apr',
  },
  {
    id: 'dest_02',
    city: 'Amalfi Coast',
    country: 'Italy',
    tagline: 'Cliffside Villages & Tyrrhenian Sea',
    estCostPerDay: 320,
    image: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=600&q=80',
    category: 'Coastal',
    rating: 4.8,
    bestMonths: 'May - Sep',
  },
  {
    id: 'dest_03',
    city: 'Reykjavik',
    country: 'Iceland',
    tagline: 'Geysers, Glaciers & Northern Lights',
    estCostPerDay: 280,
    image: 'https://images.unsplash.com/photo-1504893524553-b855bce32c67?auto=format&fit=crop&w=600&q=80',
    category: 'Adventure',
    rating: 4.9,
    bestMonths: 'Sep - Mar',
  },
  {
    id: 'dest_04',
    city: 'Santorini',
    country: 'Greece',
    tagline: 'Whitewashed Aegean Architecture',
    estCostPerDay: 290,
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=600&q=80',
    category: 'Romantic',
    rating: 4.7,
    bestMonths: 'Apr - Oct',
  },
];

export const MOCK_BUDGET_SUMMARY = {
  totalBudget: 14900,
  totalAllocated: 11000,
  totalSpent: 8850,
  currency: 'USD',
  currencySymbol: '$',
  categories: [
    { name: 'Flights & Rail', percentage: 40, amount: 3540, color: '#4F46E5' },
    { name: 'Accommodations', percentage: 35, amount: 3097, color: '#6366F1' },
    { name: 'Activities & Dining', percentage: 18, amount: 1593, color: '#F97316' },
    { name: 'Buffer & Transit', percentage: 7, amount: 620, color: '#94A3B8' },
  ],
};

export const MOCK_ACTIVITIES = [
  {
    id: 'act_1',
    text: 'Hotel confirmed in Tokyo (Shinjuku Granbell)',
    timestamp: '2 hours ago',
    icon: 'Hotel',
  },
  {
    id: 'act_2',
    text: 'Shinkansen bullet train pass booked for Kyoto-Osaka route',
    timestamp: 'Yesterday',
    icon: 'Train',
  },
  {
    id: 'act_3',
    text: 'Sarah added 4 new food recommendations to Paris itinerary',
    timestamp: '2 days ago',
    icon: 'UserPlus',
  },
];
